grafana:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - grafana.monitoring.com
    path: /
prometheus:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - prometheus.monitoring.com
    path: /
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: windows-exporter
      static_configs:
      - targets:
        - <windows_ip>:9182
